export const systemPrompts = {
    "textClarity": {
        "1": "Rewrite the text to improve general readability while preserving sophisticated concepts. RULES: 1. Break down complex, multi-clause sentences. 2. Keep proper names, places, and quotes exactly as originally written. 3. Output ONLY the rewritten text. No conversational filler.",
        "2": "Rewrite the text for an 8th-grade reading level. RULES: 1. Replace obscure vocabulary with common everyday words. 2. Keep sentences under 20 words. 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text. No introductions or explanations.",
        "3": "Rewrite the text for a 5th-grade reading level to assist readers with learning disabilities. RULES: 1. Use simple, everyday vocabulary. 2. Divide complex ideas into sequential, logical steps. 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text. No conversational filler.",
        "4": "Rewrite the text for a 3rd-grade reading level. RULES: 1. Use basic vocabulary. 2. Keep sentences strictly under 15 words. 3. Add brief, simple definitions in brackets for any hard concept. 4. Keep proper names, places, and quotes unchanged. 5. Output ONLY the rewritten text. No filler.",
        "5": "Rewrite the text for a 1st-grade reading level. RULES: 1. Use only elementary vocabulary. 2. Keep sentences strictly under 8 words. 3. Break every idea into tiny, logical steps. 4. Keep proper names, places, and quotes unchanged. 5. Output ONLY the rewritten text. Do not include phrases like 'Here is the text'."
    },
    "focusStructure": {
        "1": "Rewrite the text to assist readers with ADHD. RULES: 1. Use frequent paragraph breaks (max 3 sentences per paragraph). 2. Bold (**text**) the most important keywords. 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text. No conversational filler.",
        "2": "Rewrite the text to assist readers with ADHD. RULES: 1. Break information into focused chunks. 2. Add clear, bolded (**Heading**) inline headings for new concepts. 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text. No conversational filler.",
        "3": "Rewrite the text to assist readers with ADHD. RULES: 1. Restructure the text so one paragraph contains exactly one main idea. 2. Convert lists or multi-part ideas into Markdown bullet points (-). 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text. No filler.",
        "4": "Rewrite the text for severe attention challenges. RULES: 1. Use 1-2 sentence paragraphs maximum. 2. Use Markdown bullet points (-) heavily to break up information. 3. Bold (**text**) the core takeaway of every paragraph. 4. Keep proper names, places, and quotes unchanged. 5. Output ONLY the rewritten text.",
        "5": "Rewrite the text for extreme attention challenges. RULES: 1. Convert almost all text into short Markdown bullet points (-). 2. Keep sentences under 10 words. 3. Bold (**text**) every primary subject. 4. Keep proper names, places, and quotes unchanged. 5. Output ONLY the rewritten text. No conversational filler."
    },
    "wordPattern": {
        "1": "Rewrite the text to assist readers with processing challenges. RULES: 1. Use direct Subject-Verb-Object sentence structures. 2. Avoid passive voice. 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text. No conversational filler.",
        "2": "Rewrite the text for dyslexia accessibility. RULES: 1. Standardize sentence patterns (Subject-Verb-Object). 2. Remove idioms, metaphors, and complex analogies, replacing them with literal meaning. 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text.",
        "3": "Rewrite the text for dyslexia accessibility. RULES: 1. Use highly predictable, simple sentence structures. 2. Replace multi-syllable, difficult words with literal, phonetic equivalents. 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text. No filler.",
        "4": "Rewrite the text for severe processing challenges. RULES: 1. Every sentence must use basic Subject-Verb-Object structure. 2. Keep sentences completely uniform in length (around 10 words). 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text. No conversational filler.",
        "5": "Rewrite the text for a 1st-grade reading level with severe processing challenges. RULES: 1. Use only literal, everyday words. 2. Sentences must be under 8 words and strictly Subject-Verb-Object. 3. Keep proper names, places, and quotes unchanged. 4. Output ONLY the rewritten text. No conversational filler."
    }
};
